### ISSUE TITLE
Nitpick

### ISSUE THREAD

**Issue by paul-bjorkstrand** [spencerwi/Comparators.js#12]
I like this, and thank you for implementing something like this. More than a handful of times I have rolled my own comparisons (usually by doing bit-shifting for precedence - the more left-shifted the comparison value, the more important it was and adding the values up). This way is far more readable and would have made it easier for less senior team members understand and troubleshoot the logic more easily.

I do want to nitpick the Readme a bit. It mentions:

> When Java 8 rolled out, it brought with it a Comparator interface...

I suggest slightly changing this to

> When Java 8 rolled out, it brought with it several enhancements to the Comparator interface...

While Java 8 did bring a lot of enhancements to `java.util.Comparator`, the interface has existed since (at least) Java 1.2 ([this][1] is the earliest reference I could find). As I said, just a nit, not a huge issue.

The fact that you made roughly equivalent code in uncompressed, unminified 2.2kb is damn impressive, with zero dependencies to boot. I will be keeping this in my tool-belt when I have some complex sorting I need to do in a front end in a future project.

Again, thank you for this and great work.

[1]: https://javaalmanac.io/jdk/1.2/api/java/util/Comparator.html

**Comment by spencerwi** [comment]
Hey, thanks for the kind words! Next time I go to cut a release (probably for another round of dependabot security PRs), I'll drop in those README changes. Thanks!
